CREATE TABLE IF NOT EXISTS rules (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS destination_mapping (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);



